[fix] Emitting events from different coroutines
wireapp/wire-android-reloaded pull request #266
Opened 2021-10-04 10:35 UTC by ohassine

## Current Issues
Emitting events in `flow { }` builder from different coroutines scope will throw an `IllegalStateException` 

## Solution
To mitigate this restriction, I used [channelFlow](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/channel-flow.html)

2021-10-05 06:52 UTC, vitorhugods approved these changes

2021-10-05 10:57 UTC, vitorhugods requested changes
As discussed, waiting proposed changes regarding how we deal with closing the flow.

2021-10-06 13:53 UTC, mejdoo approved these changes
Sounds good 👍 I left some minor questions.

2021-10-06 13:53 UTC, mejdoo commented on app/src/main/kotlin/com/wire/android/core/events/datasource/EventDataSource.kt
> +        val liveEventsFlow = currentClientIdFlow.flatMapMerge { clientId ->
Out of curiosity, what's the difference between `liveEvents` and `pendingEvents`?

2021-10-06 14:15 UTC, ohassine commented on app/src/main/kotlin/com/wire/android/core/events/datasource/remote/NotificationRemoteDataSource.kt
> +            }.take(1).map { allNotifications(clientId, notificationId) }
And we added `take()` to cancel the flow after being consumed

2021-10-06 14:16 UTC, merged