feat: generate build configs
wireapp/wire-android-reloaded pull request #636
Opened 2022-06-01 08:05 UTC by MohammedMokresh

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-06-01 12:20 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3511865)(3511865)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3511865)(3511865)-dev-release.apk)

2022-06-01 17:15 UTC, vitorhugods requested changes
I like it a lot! 🥰
Really well done and clean.

I guess a lot of these feature flags will go to space for now, but at least we have a way cleaner way of doing this, compared to current Scala app.

Just some suggestions to make it tighter and a big reminder that this should not be merged before https://github.com/wireapp/kalium/pull/557.

I updated the PR description to mention the blocking PR.

2022-06-02 08:15 UTC, ohassine commented on buildSrc/src/main/kotlin/Configs.kt
> +    PROD("prod", ConfigType.FLAVOUR_CONFIG);
And extract this to VariantConfigs ?

2022-06-02 08:15 UTC, ohassine commented on buildSrc/src/main/kotlin/scripts/variants.gradle.kts
> +                }
Isn't the same thing, can't we do for both: 
`""""${buildtimeConfiguration?.configuration?.get(configs.value).toString()}""""`

2022-06-02 08:35 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519155)(3519155)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519155)(3519155)-dev-release.apk)

2022-06-02 09:08 UTC, MohammedMokresh commented on app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
> +            appLockTimeout = BuildConfig.APP_LOCK_TIMEOUT
yeah for the urls, I spoke with Mohamad , and I will update it after he merge the api versioning 
or he will update this if I merged first

2022-06-02 09:21 UTC, AndroidBob commented
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3519434)(3519434)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3519434)(3519434)-dev-release.apk)

2022-06-02 13:21 UTC, AndroidBob commented
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/7/) **failed**.

2022-06-03 07:23 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3527364)(3527364)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3527364)(3527364)-dev-release.apk)

2022-06-03 09:21 UTC, AndroidBob commented
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3528077)(3528077)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3528077)(3528077)-dev-release.apk)

2022-06-07 13:02 UTC, ohassine approved these changes
lgtm 🚀

2022-06-08 09:45 UTC, yamilmedina approved these changes
Great work Big Mo! nice work in gradle world 👏

2022-06-08 12:42 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-636/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3572468)(3572468)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3572468)(3572468)-dev-release.apk)

2022-06-08 12:42 UTC, merged