feat: Display blocked user properly
wireapp/wire-android-reloaded pull request #820
Opened 2022-08-02 14:36 UTC by borichellow

# Second part of [Task-1593](https://wearezeta.atlassian.net/browse/AR-1593) (there will be one more)

# What's new in this PR?

Blocked user is displayed properly in all the places (search, conversation, conversation participants, profile, etc.)

### Attachments (Optional)

![photo_5424655604972110844_y](https://user-images.githubusercontent.com/6539347/182400942-378d9e4b-2506-4ccc-86f2-30a960fcc8e8.jpeg)

![photo_5424655604972110842_y](https://user-images.githubusercontent.com/6539347/182400943-20fb519f-de18-4880-a254-d506b32be4fd.jpeg)

![photo_5424655604972110843_y](https://user-images.githubusercontent.com/6539347/182400946-43f29b2e-2fea-4f8a-8381-064b3e40563d.jpeg)

![photo_5424655604972110841_y](https://user-images.githubusercontent.com/6539347/182400948-6837fbba-6a0b-4b79-9ad7-3768d45d665a.jpeg)

2022-08-02 14:44 UTC, AndroidBob commented
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/1/) **failed**.

2022-08-02 15:00 UTC, AndroidBob commented
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/2/) **failed**.

2022-08-02 18:00 UTC, AndroidBob commented
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/3/) **failed**.

2022-08-03 08:30 UTC, AndroidBob commented
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4054796)(4054796)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4054796)(4054796)-dev-release.apk)

2022-08-03 09:31 UTC, AndroidBob commented
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4055166)(4055166)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4055166)(4055166)-dev-release.apk)

2022-08-04 09:39 UTC, gongracr requested changes
I added a few non-important comments, mostly about separating code concerns to other files. But massive work here 💪

2022-08-04 09:39 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
> +private fun AttachmentOptions(
Maybe this is a good moment to rename and extract this to a separate `MessageAttachmentOptions` file?

2022-08-04 09:39 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
> +}
Same than above. Can we move to a different file? Maybe one grouping all the MessageComposeActions ?

2022-08-04 09:39 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
> +private fun UserIsBlockedMessage() {
As this is not really a conditional compose object, my suggestion would be to rename it to `BlockedUserMessage` and move it to a separate file.

2022-08-08 08:59 UTC, borichellow commented on app/src/main/kotlin/com/wire/android/ui/common/UserBadge.kt
> +fun UserBadge(membership: Membership, connectionState: ConnectionState? = null, startPadding: Dp = 0.dp) {
good idea

2022-08-08 11:51 UTC, AndroidBob commented
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4099196)(4099196)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4099196)(4099196)-dev-release.apk)

2022-08-08 14:07 UTC, gongracr approved these changes
I added some tiny comments. But looking in great shape. Thx for the changes 🙏 🥮 ☕

2022-08-08 14:07 UTC, gongracr commented on app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
> +            .height(56.dp)
Magic number?

2022-08-08 15:22 UTC, AndroidBob commented
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4100473)(4100473)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4100473)(4100473)-dev-release.apk)

2022-08-10 09:00 UTC, AndroidBob commented
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4115461)(4115461)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4115461)(4115461)-dev-release.apk)

2022-08-10 09:10 UTC, borichellow commented on app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
> +        }
yes, finally i updated kotlin plugin and now it doesn't change empty `{}` :)

2022-08-10 09:27 UTC, AndroidBob commented
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-820/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4115623)(4115623)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4115623)(4115623)-dev-release.apk)

2022-08-10 09:28 UTC, merged